apiVersion: v1
kind: PersistentVolume
metadata:
  name: fileserver-magento-media
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /magento
    server: 172.26.54.18
